[base]
name = multiscale_run

[tox]
envlist =
    check-packaging
    lint
    docs

# we use venv so we pick the correct libs
[testenv]
sitepackages = true
pass_env = *
deps =
    pytest

[testenv:docs]
changedir = {toxinidir}
extras = docs
commands = sphinx-build -W --keep-going docs docs/build/html

[testenv:format]
deps =
    ruff
    codespell
commands =
    ruff check --fix
    codespell --config .codespellrc -i 3 -w {[base]files} README.md docs/ --skip=docs/build/*

[testenv:unit]
deps =
    {[testenv]deps}
    pytest-profiling
setenv =
    NEURON_INIT_MPI=0
commands =
    pytest --ignore=old {posargs:tests/unit}

; [testenv:unit]
; deps =
;     {[testenv]deps}
;     pytest-profiling
;     mpi4py --no-binary=mpi4py
;     h5py --no-binary=h5py
; setenv =
;     NEURON_INIT_MPI=0
; commands =
;     python -c "import h5py; print('MPI support' if getattr(h5py.get_config(), 'mpi', False) else 'No MPI support')"
;     ; pytest --ignore=old {posargs:tests/unit}

; [testenv:fixlint]
; skip_install = True
; deps =
;     ruff
; commands =
;     ruff format
;     ruff check {posargs:--fix}

; [testenv:check-packaging]
; skip_install = true
; deps =
;     build
;     twine
; commands =
;     python -m build -o {envtmpdir}/dist
;     twine check {envtmpdir}/dist/*



