[base]
name = multiscale_run

[tox]
envlist =
    check-packaging
    lint
    docs

[testenv]
pass_env = *
deps =
    pytest

[testenv:format]
skip_install = true
deps =
    ruff
    codespell
commands =
    ruff check --fix
    codespell --config .codespellrc README.md docs/ --skip="docs/build/*"

[testenv:unit]
deps =
    {[testenv]deps}
    pytest-profiling
setenv =
    NEURON_INIT_MPI=0
commands =
    pytest --ignore=old {posargs:tests/unit}

