name: MPI venv test

on:
  pull_request:

jobs:
  mpi-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mpich libmpich-dev hdf5-tools


      - name: Compile and run MPI test
        run: |
          which mpicc
          which mpicxx
          which mpiexec
          which mpirun
          echo "----"
          mpiexec --version
          mpicxx mpi_test.cpp -o mpi_test
          mpiexec -np 2 ./mpi_test
          echo "----"
          mpicc mpi_test.c -o mpi_test_c
          mpirun -np 2 ./mpi_test_c


      # - name: Setup Python 3.11
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: "3.11"

      # - name: Create venv and install mpi4py
      #   run: |
      #     python -m venv venv
      #     . venv/bin/activate
      #     python -m pip install --upgrade pip setuptools wheel
      #     # compile mpi4py with the system mpicc
      #     MPICC=/usr/bin/mpicc pip install --no-binary=mpi4py mpi4py

      # - name: Activate venv
      #   run: |
      #     echo "${{ github.workspace }}/venv/bin" >> $GITHUB_PATH
      #     echo "VIRTUAL_ENV=${{ github.workspace }}/venv" >> $GITHUB_ENV

      # - name: Run MPI test
      #   run: |
      #     which python
      #     mpirun -np 2 \
      #       -env PATH "$PATH" \
      #       -env LD_LIBRARY_PATH "$LD_LIBRARY_PATH" \
      #       -env VIRTUAL_ENV "$VIRTUAL_ENV" \
      #       ${{ github.workspace }}/venv/bin/python mpi_test.py
